apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  labels:
    app: MyApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: is7aq/lap:4
